### ISSUE TITLE
Is field type mapping possible ?

### ISSUE THREAD

**Issue by Aardvark71** [AgileWorksOrg/elasticsearch-river-csv#41]
I might have missed it, but it looks like all fields coming in through the river-csv are strings.

I have used the following minimal PUT request : 

```
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "C:\\localdata\\COUNTER3",
        "first_line_is_header":"true"
    }
}
```

Can the [fields] parameter be used to specify a field type mapping too?

Or should I specify the mapping on the index with the Elasticsearch mapping api ?

**Comment by rmoff** [comment]
For anyone else with this question: 
You can also use dynamic templates to match column names (eg "COUNT") and set the data types (eg LONG) accordingly: 
http://www.elastic.co/guide/en/elasticsearch/guide/current/custom-dynamic-mapping.html#dynamic-templates
http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-root-object-type.html#_dynamic_templates
