### ISSUE TITLE
How to use the plugin in the client

### ISSUE THREAD

**Issue by QAqua** [AgileWorksOrg/elasticsearch-river-csv#43]
I have two machine, 

<b>one</b> has installed elasticsearch service(servier) and the elasticsearch-river-csv plugin;while <b>the other</b> has not and served as a client.

I usually run <b>curl -X<REST Verb> </b>on the client.

But when i run the sample in the readme, can not import csv successfully
>ps1: sample can ran successfully on the server)
ps2:  log (only received two lines)

>>[2015-01-09 03:16:18,999][INFO ][cluster.metadata         ] [Big Man] [river2] creating index, cause [auto(index api)], shards [5]/[1], mappings []
[2015-01-09 03:16:19,461][INFO ][cluster.metadata         ] [Big Man] [river2] update_mapping [my_csv_river] (dynamic)

Is this for sure? because i have not installed plugin on the client?
<b>what else should i do , can i use curl -X<REST Verb> on the client</b>.

Thank you for your attention and your good app.

==sample tested on the server (OK)================================
curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/tmp",
        "first_line_is_header":"true"
    }
}'
==sample tested on the client (failed)================================
curl -XPUT localhost:9200/river2/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/home/aqua/tmp",
        "first_line_is_header":"true"
    }
}'

**Comment by xxBedy** [comment]
Elasticsearch run in clustered environment. It means that csv-river must be installed on all machines in the cluster, and all machines must have access to shared folder with csv files. When instance of ES where river is running failed, ES start new river instance on other server in the cluster. 
Try to ask in elasticsearch forum if it's possible to lock river on specific server(s).
