### ISSUE TITLE
Disable polling / run on demand

### ISSUE THREAD

**Issue by rmoff** [AgileWorksOrg/elasticsearch-river-csv#48]
This is awesome, thank you!

Is there a way to disable polling entirely, and instead trigger the river by an API call? 

I'm guessing I can set poll to a long time period, but it feels a bit of a cheat ;-)

**Comment by vtajzich** [comment]
It's a plugin for ES, not an app. It's loaded as part of ES so it's not wise to expose some API. Use polling for this. Try to find value which fits your needs (10s, 5 mins, 2 days...)

**Comment by rmoff** [comment]
I meant something like this : https://github.com/jprante/elasticsearch-river-jdbc#suspend

It's no biggie, I can just delete/redefine the river as needed each time. 

Thanks.
