### ISSUE TITLE
Mappings update

### ISSUE THREAD

**Issue by BalachanderGS** [AgileWorksOrg/elasticsearch-river-csv#51]
How do I update the mappings I have created in the river_meta ? I changed the order of the columns in mappings and restarted ES as well, but I see the old order in the logs

Using configuration: org.agileworks.elasticsearch.river.csv.Configuration(/usr/local/data, .*.csv, false, [ekv_raw, ekv_flight, event_id, cookie_id, dpId, vertical, activity_group, activity, eventDateTime, departureDate, returnDate, origin, destination, destination_country_code, destination_state, destination_city, carrier, cabinClassGroup, currency, duration, travelers, airFare, bookedDate], 1m, ztmp_inventory_tool_sample, invData, 10000, \, ", ,, 10, 5, id, null, null, null, null, null, UTF-8)

Any suggestions to clear river settings and recreate the mappings?

**Comment by vtajzich** [comment]
delete river and create it once more again w/ proper mapping.
