### ISSUE TITLE
Data type is always String

### ISSUE THREAD

**Issue by tobilg** [AgileWorksOrg/elasticsearch-river-csv#55]
I have a problem that the CSV River ignores the mapping settings, and just inserts String values. I noticed that this behavior is probably caused by the code line found at https://github.com/AgileWorksOrg/elasticsearch-river-csv/blob/master/src/main/groovy/org/agileworks/elasticsearch/river/csv/OpenCSVFileProcessor.groovy#L78

`builder.field((String) fieldName, line[position])`

It's not really clear to me how I can achieve that I can somehow either define what data type should be used, or that the mapping is adhered.

Can you give me some hints? Is this possible at all?

**Comment by ESPNSTI** [comment]
This functionality is definitely working for me, I have several rivers with indexes and mappings that have number and date fields.

Check that your index, mapping and index configuration is correct.

Here is a river create script that I use (with the index and field names renamed).

curl -XPUT localhost:9200/myindex

curl -XPUT localhost:9200/myindex/_mapping/myType -d '{
    "myType" : {
        "properties" : {
            "field1" : {"type": "string", "index" : "not_analyzed" },
            "field2": {"type": "integer", "index" : "not_analyzed"},
            "field3": {"type": "long", "index" : "not_analyzed"},
            "field4": {"type": "string", "index" : "not_analyzed"},
            "field5": {"type": "date", "index" : "not_analyzed", "format" : "yyyy-MM-dd HH:mm:ss.SSSSSSSSS"}
        }        
    }
}'

curl -XPUT localhost:9200/_river/myindex/_meta -d '{
    "type" : "csv",
    "csv_file" : {
        "folder" : "C:\\MyFolder\\",
        "first_line_is_header":"true",
        "filename_pattern" : "MyFile.*\\.txt",
        "poll": "15m",
        "field_separator": "|",
        "field_id" : "MyIdField"
    },
    "index" : {
        "index":"myindex",
        "bulk_size":10000,
        "bulk_threshold":10,
        "type":"myType"
    } 
}'

**Comment by tobilg** [comment]
Thanks for your reply! Unfortunately it doesn't work for me... I tried to use your example with ES 1.4.4.

I created the following test.csv file

```
field1;field2;field3;field4;field5
test;1;3424352534534545;test;2015-01-01 12:00:00.000000000
```

Then, I ran the following commands in Marvel:

```
PUT /myindex

PUT /myindex/myType/_mapping
{
    "myType" : {
        "properties" : {
            "field1" : {"type": "string", "index" : "not_analyzed" },
            "field2": {"type": "integer", "index" : "not_analyzed"},
            "field3": {"type": "long", "index" : "not_analyzed"},
            "field4": {"type": "string", "index" : "not_analyzed"},
            "field5": {"type": "date", "index" : "not_analyzed", "format" : "yyyy-MM-dd HH:mm:ss.SSSSSSSSS"}
        }        
    }
}

PUT /_river/myindex/_meta
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "D:/tmp/Test",
        "first_line_is_header":"true",
        "filename_pattern" : "test.*\\.csv",
        "poll": "1m",
        "field_separator": ";",
        "field_id" : "MyIdField"
    },
    "index" : {
        "index":"myindex",
        "bulk_size":10000,
        "bulk_threshold":10,
        "type":"myType"
    } 
}

GET /myindex/myType/_search
```

The output of the last command is:

```
{
   "took": 40,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "myindex",
            "_type": "myType",
            "_id": "4c860a39-be2e-44ad-8fc2-4627cc7eb579",
            "_score": 1,
            "_source": {
               "field1": "test",
               "field2": "1",
               "field3": "3424352534534545",
               "field4": "test",
               "field5": "2015-01-01 12:00:00.000000000"
            }
         }
      ]
   }
}
```

Unfortunately, everything is mapped as Strings, as I wrote. Did I do something wrong?

**Comment by ESPNSTI** [comment]
This all works fine for me.
I recently switched to ES 1.5.0, but this also works on 1.4.4.

Is the mapping still correct when you query it?
<pre>curl -XGET localhost:9200/myindex/myType/_mapping</pre>

How are you confirming that the field types are strings?
I'm looking at it through Kibana

![kibana index](https://cloud.githubusercontent.com/assets/11448987/6964923/456eb6fe-d913-11e4-9f2e-1732e1f9dea3.png)

**Comment by tobilg** [comment]
Sorry for the late feedback. The mapping is left unchanged, and when I query `GET /myindex/myType/_search` the output as written in my last comment is returned. In the `_source` field, I see only strings.

As I'm a relative beginner with ElasticSearch, how can/should I check the *real* data types?

**Comment by ESPNSTI** [comment]
Ok, I misunderstood, you're referring to the JSON types within _source and not as I thought, the ES field types.
I'm very new with ES as well.

It looks like ES does support non-string properties within _source, but the CSV river does not.
I don't know what's involved with adding that to the river, but I can't imagine it would be simple.

**Comment by vtajzich** [comment]
Pleade, see http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

_source contains strings, however it doesn't mean that ES see strings as well. You can provide your data type mapping to let ES know how the data should be treated.

**Comment by vtajzich** [comment]
As data are parsed from CSV where are no data types at all we cannot do anything about it. It's not even needed. Providing data type mapping to ES is sufficient

**Comment by tobilg** [comment]
I still think this is a slight problem, but maybe it's just me... I think it would be easy to add a (toggleable) data type recognition from source values (I know that CSV is just strings on the first hand), for example with RegExp pattern matching.

Basically, only the core data types (string, number (with subtypes) and date) should be necessary.

My use case would be that I want to use imported data also in web applications, and therefore I'd also need to be able to get the "mapped" data types.

Using aggregations like 

```
POST /myindex/myType/_search?search_type=count
{
  "query": {
    "match_all": {}
  },
  "aggs": {
      "max_field3": {
          "max": {
              "field": "field3"
          }
      }
  }
}
```

return the right data type though:

```
{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "max_field3": {
         "value": 3424352534534545
      }
   }
}
```

but getting the document by id

`GET /myindex/myType/f030192e-c94e-4ed3-8e88-c70c1af98ffa``

just return the `_source` with string data types (which is understandable, but contrary to my desired use case).

**Comment by vtajzich** [comment]
I use the data in web app as well. As the data flows through JSON parser framework (e.g. Jackson) I don't care about types as they are being parsed according to my model.

**Comment by tobilg** [comment]
As I'm using Node.js I do care what data type the fields have, because JSON can directly be converted to objects (with String-only data types currently). And that's my issue...

**Comment by vtajzich** [comment]
Could you share your data file, mapping and request so we can try to look into it?

**Comment by tobilg** [comment]
You can find everything in my above comments. Thanks a lot in advance!
