### ISSUE TITLE
Gitches with two double quotes 

### ISSUE THREAD

**Issue by NicolasYDDER** [AgileWorksOrg/elasticsearch-river-csv#56]
Hi folks,

I have a very strange behavior when I use double quote to escape double quote ( e.q : ""content"").

This is my csv's cells involved in my issue:
cell one :``"371620ZV001 (DTJZL MDPB) - UDYAQNIANP VBRHVEXHOWIC EO HVWQBZ : QEF  2013-12-30 22:30 VN AQHH FRQ WMABP LF GSXYPMA OQ RTIQAGUOELL ""T:\HTTUMNC\"":ZT TZXGDJ B?ADEHW YWMLSQUR TIQ BHONLSUACNH SH MAB : 1 1 WQLZQO(R) NRVX QM VL FOJLVYTLYA",``

cell two : ``UTDRXSPA < PFSB Q3906181,``

cell tree: ``08/01/2014 15:20:24 ZQOMOE/OLHIRL (QSQEPX, EHBVJA RABFH): 08/01/2014 15:19:57 FWUSUQ/URNOXR (WYWQVD, QNHBPG XGHLN) ** HECMMCJJ NQOQQVIJ / JZAAEHTU ** : YMMJPWU, RL LQD A : 5334645 Z FVH YXHQCO XR : 07-01-14 11:01 XHXYOW QI SRQ : YLBD SGJEYQ : 371620 CAUYGHB : UQXVX NZ MZQHF TV MIPNXGME THGFVPBDVLFVT",``

result in ES: 
``"371620ZV001 (DTJZL MDPB) - UDYAQNIANP VBRHVEXHOWIC EO HVWQBZ : QEF  2013-12-30 22:30 VN AQHH FRQ WMABP LF GSXYPMA OQ RTIQAGUOELL "T:\HTTUMNC\"":ZT TZXGDJ B?ADEHW YWMLSQUR TIQ BHONLSUACNH SH MAB : 1 1 WQLZQO(R) NRVX QM VL FOJLVYTLYA",UTDRXSPA < PFSB Q3906181,08/01/2014 15:20:24 ZQOMOE/OLHIRL (QSQEPX,``

I suppose this block is incriminated in my glitch because 2 double quote are still present in ES field.
``""T:\HTTUMNC\"" ``

Some one could help me to solve that ?

BR

Nicolas.

**Comment by vtajzich** [comment]
You should set ```quote_character``` to some character which is not part of your data (e.g. # or $ ... )

**Comment by vtajzich** [comment]
@NicolasYDDER do you need further help?
