### ISSUE TITLE
Index is not created

### ISSUE THREAD

**Issue by subburaj45** [AgileWorksOrg/elasticsearch-river-csv#59]
I am using the following command to import data from csv file.

curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/home/testuser/river_test",
        "filename_pattern" : ".*\\.csv$",        
        "first_line_is_header" : "true",
        "field_separator" : ",",        
        "charset" : "UTF-8"        
    },
    "index" : {
        "index" : "myvar_model",
        "type" : "csv_type",
        "bulk_size" : 100,
        "bulk_threshold" : 10
    }
}'

But the index is not created. I searched for documentaion i cant found. I am using elasticsearch version:1.2.4 and plugin version 2.1.0.

**Comment by vtajzich** [comment]
Take a look on readme. According to version table you should be using plugin of version 2.0.2. 

If you want to use newer version of plugin, you must upgrade ES.

**Comment by subburaj45** [comment]
first time i am using the following command:

curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/home/testuser/river_test",
        "filename_pattern" : ".*\\.csv$",        
        "first_line_is_header" : "true",
        "field_separator" : ",",        
        "charset" : "UTF-8"        
    },
    "index" : {
        "index" : "myvar_model",
        "type" : "csv_type",
        "bulk_size" : 100,
        "bulk_threshold" : 10
    }
}'
The index "myvar_model" is created.
ANd now i want to create new index and the csv data is in another folder, so i used the following commaand:
curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/home/testuser/myvar_model",
        "filename_pattern" : ".*\\.csv$",        
        "first_line_is_header" : "true",
        "field_separator" : ",",        
        "charset" : "UTF-8"        
    },
    "index" : {
        "index" : "myvar_xxxxx",
        "type" : "csv_type",
        "bulk_size" : 100,
        "bulk_threshold" : 10
    }
}'

Now the index is not crated.Why??

**Comment by xxBedy** [comment]
Hi,

You must delete current river configuration on localhost:9200/_river/my_csv_river/_meta or use different URL for second river configuration.

Bedy

**Comment by subburaj45** [comment]
Different URL means whether i have to change the typ meta to meta1?? I am new bie to this so please calrify this. How can i delete current river configuration.

**Comment by xxBedy** [comment]
You can delete river configuration with this command:

curl -XDELETE http://localhost:9200/_river/my_csv_river <http://localhost:9200/_river/my_csv_river>

**Comment by subburaj45** [comment]
Thanks  @ xxBedy  i got it..

**Comment by subburaj45** [comment]
One more clarification is it posible to create index with mapping using river??

**Comment by subburaj45** [comment]
@xxBedy For first time i deleted the river configuration and index it works fine. But when i tried deleting for second time the river configuration and tried for indexing, now the index is not created..

**Comment by subburaj45** [comment]
@xxBedy I found the solution.In  my folder the file name is changed to "ModelScore.csv.processing.imported" i changed to "ModelScore.csv".Now it works.

**Comment by subburaj45** [comment]
@xxBedy  mapping is not applying the index.Is there any solution for this??

**Comment by xxBedy** [comment]
No. You must create index with mapping before creating river configuration.
CSV river is not responsible for creating mapping. There is no reason to have this functionality in CSV river when there is standard API for that.
See: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html

**Comment by subburaj45** [comment]
@xxBedy Thanks .One more clarification. Suppose considser the following configuration
curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
"type" : "csv",
"csv_file" : {
"folder" : "/home/testuser/river_test",
"filename_pattern" : ".\.csv$",

"first_line_is_header" : "true",
"field_separator" : ",",

"charset" : "UTF-8"

},
"index" : {
"index" : "myvar_model",
"type" : "csv_type",
"bulk_size" : 100,
"bulk_threshold" : 10
}
}'

Now in the folder /home/testuser/river_test i have a.csv file. Suppose consider i add 1 more csv b.csv file. whether the river automatically trigger to index that. Or otherwise i have to configure once again.

**Comment by vtajzich** [comment]
River is configured to run periodically. You can set how often it should check for new files to index. Default value is 60 minutes.

**Comment by xxBedy** [comment]
River check folder in specified interval (parameter pool: 60minutes is default) and looking for file specified by filename_pattern.
There is no need to configure river again. Just put a.csv and then b.csv and river will index both.

Bedy

**Comment by subburaj45** [comment]
@xxBedy thanks a lot man for your valuable time.
