### ISSUE TITLE
Disable the pool parameter

### ISSUE THREAD

**Issue by subburaj45** [AgileWorksOrg/elasticsearch-river-csv#60]
By default the pool parameter is set to 60 minutes. I want to disable that parameter so that i have to manually trigger csv-river to index the data. Is it possible?

**Comment by xxBedy** [comment]
No you can't. 
But you can configure river to pull directory for import file every one minute (or less). Then copy file to the folder when you want index data. 


Odesláno z iPhonu

18. 8. 2015 v 7:57, subburaj45 <notifications@github.com>:
