### ISSUE TITLE
Support for sub folder while pooling

### ISSUE THREAD

**Issue by subburaj45** [AgileWorksOrg/elasticsearch-river-csv#62]
Whether csvrover will support for subfolder while pooling?
 
My Folder structure for csv files is as follows:

ParentFolder
  subfolder1
    a.csv
  subfolder2
    b.csv

I can configure a river for ParentFolder. suppos if i put csv file into subfolder2 the river configuration will work automatically?? Or i have to configure for each subfolder????

**Comment by xxBedy** [comment]
Hi,
You can configure two or more rivers. One for each folder you want to index. 

Bedy

Odesláno z iPhonu

1. 9. 2015 v 7:18, subburaj45 <notifications@github.com>:
