### ISSUE TITLE
Notification for csv indexed

### ISSUE THREAD

**Issue by subburaj45** [AgileWorksOrg/elasticsearch-river-csv#64]
Suppose i have configured a csv-river for a folder. In that within  particular time new csv data are uploaded means how can i get the status whether the csv file is index or not(status of the file)??

Whether i have to use the following option:
"script_before_file": "/path/to/before_file.sh",
        "script_after_file": "/path/to/after_file.sh"

I have to update the database that the file is indexed. So whether i have to write shell script to do that??

**Comment by vtajzich** [comment]
Hi, please take a look on readme:

```
takes list of all file paths as arguments

"script_before_all": "/path/to/before_all.sh"
"script_after_all": "/path/to/after_all.sh"

file path is argument

"script_before_file": "/path/to/before_file.sh",
"script_after_file": "/path/to/after_file.sh"

```
